version: '3.2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    volumes:
      - "./kibana.yml:/usr/share/kibana/config/kibana.yml"
      - "./etc/Sao_Paulo:/etc/localtime:ro" 
    restart: always
    environment:
      - SERVER_NAME=kibana.localhost
      - ELASTICSEARCH_HOSTS=http://elasticsearch1:9200
    ports:
      - "5601:5601"
    networks:
      - elastic
    external_links:
      - elasticsearch1:elasticsearch1
      - elasticsearch2:elasticsearch2
      - elasticsearch3:elasticsearch3
      
networks:
    elastic:
        external: true


