version: '3.2'
services:
  kafka1:
    image: wurstmeister/kafka
    volumes:
      - "./etc/Sao_Paulo:/etc/localtime:ro" 
    command: [start-kafka.sh]
    depends_on:
      - zoo1
      - zoo2
    networks:
      - elastic
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000000"
      KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181,zoo2:2181
      KAFKA_CREATE_TOPICS: "log:3:3"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  kafka2:
    image: wurstmeister/kafka
    volumes:
      - "./etc/Sao_Paulo:/etc/localtime:ro" 
    depends_on:
      - zoo1
      - zoo2
    networks:
      - elastic
    ports:
      - "9093:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000000"
      KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181,zoo2:2181
      KAFKA_CREATE_TOPICS: "log:3:3"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  zoo1:
    image: elevy/zookeeper:latest
    volumes:
      - "./etc/Sao_Paulo:/etc/localtime:ro" 
    environment:
      MYID: 1
      SERVERS: zoo1,zoo2
    ports:
      - "2181:2181"
    networks:
      - elastic
  zoo2:
    image: elevy/zookeeper:latest
    volumes:
      - "./etc/Sao_Paulo:/etc/localtime:ro" 
    environment:
      MYID: 2
      SERVERS: zoo1,zoo2
    ports:
      - "2182:2181"
    networks:
      - elastic
     
networks:
    elastic:
        external: true

